FROM node:22.16-alpine as build
WORKDIR /app/src
COPY ./client/ .
RUN npm install -force
RUN npm run build-docker

FROM node:22.16-alpine
WORKDIR /usr/app
COPY --from=build /app/src/dist/client/ ./
CMD node server/server.mjs
EXPOSE 4000