FROM node:22.16-alpine as build
WORKDIR /app/src
COPY Client/package*.json ./
RUN npm ci
COPY ./Client/ ./
RUN npm run build

FROM node:22.16-alpine
WORKDIR /usr/app
COPY --from=build /app/src/dist/client ./
CMD node server/server.mjs
EXPOSE 4000