FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copy everything
COPY ./Api/ .
# Restore as distinct layers
RUN dotnet restore ApiSln.sln
# Build and publish a release
RUN dotnet publish ApiSln.sln -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Api.dll"]